### ISSUE TITLE
Gringott as economy plugin!

### ISSUE THREAD

**Issue by Kladdkaka** [GLServers/GLD#1]
Gringotts is a item-based economy system, instead of selling diamonds for lightstones, gringott makes diamonds the currency. You make a vault chest with the diamonds you got, and then you can use those diamonds to purchase from server shops, sending money with /money pay. We wouldn't need any sell signs, and it would promote player trading.
http://dev.bukkit.org/bukkit-plugins/gringotts/

**Comment by Joannou1** [comment]
I think we need more player input on this, as it is no doubt pretty radical.
I think it's a good idea, but how exactly does the /money pay part work if its physical items again?

**Comment by Kladdkaka** [comment]
https://github.com/MinecraftWars/Gringotts/blob/master/doc/usage.md @Joannou1
It sends the items over to the other chest I assume, it can also pay in decimals. I think if you pay Bob like 1.21 diamonds, Bob will get 1 diamond in the chest, and the plugin remembers that he got 0.21 diamonds that isn't in the chest, and if someone pays bob 0.79 diamonds (0.21 + 0.79 = 1) Bob will get 1 diamond into his chest :) Could be wrong though!

**Comment by Joannou1** [comment]
Added and configured to dev.
Works pretty well too!
