### ISSUE TITLE
Streamer Rank

### ISSUE THREAD

**Issue by Joannou1** [GLServers/GLD#11]
If we get a streamer with a considerable amount of viewers, we should give them a rank with useful utilities that would better their content and encourage further involvement.

**Comment by Kladdkaka** [comment]
Also for youtubers

**Comment by Joannou1** [comment]
Done.

Added group "Media".
Inherits Wanderer.

Perms:
fly, back, unlim sethomes, all hats, 5 min tempspawn cooldown
