### ISSUE TITLE
Rework Donation Ranks & Perks

### ISSUE THREAD

**Issue by Joannou1** [GLServers/GLD#15]
Definitely a big one here.

Here are some ideas from Kerrus:
https://privatepaste.com/f5d5314a0e

Most perks will be determined once the core stuff is set up.
Ranks will be reduced to 6-8 most likely.

**Comment by Joannou1** [comment]
Likely to remove rank worlds, or find a way to integrate/replace with the Nexus idea. 
(Player consolidation, reduce seperation/isolation)

**Comment by Joannou1** [comment]
Kerrus:

[1:08:26 AM] Kerrus Magrus: Oh, idea: Get a titles plugin
[1:08:37 AM] Kerrus Magrus: where players can get custom titles set above their heads that they donate for or earn ingame
[1:08:44 AM] Kerrus Magrus: so it's like "Kerrus, dragonslayer' for example

**Comment by TyJcksn** [comment]
I'm pretty certain that we added a plugin like this onto the skywars server.

**Comment by Joannou1** [comment]
Come up with more lightroll rewards/items.
(10-30 items that each have a 5% chance or so, so that way you'll get something)

Maybe even rename the 'points' to something else for branding.

**Comment by Joannou1** [comment]
Remove /hat or get it fixed.
Find a replacement that is either cosmetic or a utility.

**Comment by Joannou1** [comment]
Kits per rank?
If so we need to plot it out later and make it a good progression up the ranks.

**Comment by Joannou1** [comment]
Moving this to #53
