### ISSUE TITLE
New combat tag plugin

### ISSUE THREAD

**Issue by Kladdkaka** [GLServers/GLD#19]
As we all know, we haven't really had a great combattag plugin lately, but there is a amazing combattag plugin now. That makes a forcefield of glass to non-pvp areas if you're tagged. 
<img src="http://puu.sh/gznoa/e9c89cbf87.gif">
That would pretty much remove all type of pvp-related abusement, like safezoning and stuff :)
And the best thing, it works with worldguard, and also towny :D
http://www.spigotmc.org/resources/combattagplus.4775/

**Comment by Joannou1** [comment]
Brilliant, that plugin looks really fleshed out and complete.
Ima add this to the setup section

**Comment by Joannou1** [comment]
Installed, works really well!
To be further configured as needed.
