### ISSUE TITLE
More biomes

### ISSUE THREAD

**Issue by Kladdkaka** [GLServers/GLD#2]
I think we should add more biomes to the server other than desert. For example mesa, oasis, maybe very small jungles, ocean and more :)

**Comment by Joannou1** [comment]
TerrainControl has what's known as "Island Biomes".
I think they are small biomes inbetween a section of 2-3 other biomes.

You can set them to be extremely rare too.

Might be a good idea to have small sizes 'island' biomes at random.

**Comment by Joannou1** [comment]
I think we're done with biomes now.

See this post for all biomes added:
https://gldesert.com/forums/showthread.php?9811-It-s-time-to-get-GLD-rolling-again!&p=59952&viewfull=1#post59952
