### ISSUE TITLE
Achievements to make people stay a long time

### ISSUE THREAD

**Issue by Kladdkaka** [GLServers/GLD#21]
I think it would be a great idea if we had some type of achievements plugin that made custom achievements for people to do, like shoot 100 people, and the first player to do it per week gets some type of rare item (Think like poison arrows). Something like this http://www.spigotmc.org/resources/advanced-achievements.6239/

**Comment by Joannou1** [comment]
another great idea.. achievements are cool, especially if it can be competitive.
setting to core

**Comment by Joannou1** [comment]
Just installed this and set up some basic stuff..
Works pretty good aside from the command based achievements going through twice if you do the command again.. (asked the dev if he could fix this)

**Comment by Joannou1** [comment]
dev made it an option, just tested it and set up a couple of command ones.. works well!
will close this for now as I think that's a sufficient amount of achievements for now.
