### ISSUE TITLE
The Lack of Staff/Lack of Activity within the Staff Team

### ISSUE THREAD

**Issue by Jeremy9600** [GLServers/GLD#25]
I think that we should be more strict with our staff rules.

There are many, many staff members that are very inactive without it being an important enough reason to be okay. I think that we should replace these staff members with new ones; open staff apps again maybe. (Only if we can pick up the playerbase)

**Comment by Joannou1** [comment]
Well there is no doubt that we need to figure out who is still with us and go from there.
And yeah, better communication between all staff is key.

Apps may open before or after launch depending on who is still with us.

**Comment by Joannou1** [comment]
I think we are doing a great job with current staff.
As of now, I think we can close this.
