### ISSUE TITLE
Custom essentials colors :D

### ISSUE THREAD

**Issue by Kladdkaka** [GLServers/GLD#26]
Literally all servers got the default essentials colors, why not change it :D 
I made a (shitty) preview php script to make it easier a while back https://github.com/Kladdkaka/essentials-preview

**Comment by Joannou1** [comment]
wait I am confused, this changes the message colors in bulk via PHP and allows you to preview it on a webpage? Nice

**Comment by Kladdkaka** [comment]
well, it only displays the changes, to make the changes you just use notepad++ and "find all & replace all" :) but that displays everything

**Comment by Joannou1** [comment]
sweet, will have to give it a go soon :+1: 
(it's 10:21 am, and I feel like if I don't sleep now there may not be any hope for me lol)

**Comment by Joannou1** [comment]
very cool app overall, good job getting it to work!
I changed probably around 10-20 things to green/red depending on the attitude of the statement.
