### ISSUE TITLE
Better warning system

### ISSUE THREAD

**Issue by Joannou1** [GLServers/GLD#27]
I feel like the current 1 point per rule broken system is a bit off.
We could set the points required for tiers of punishments higher, and have the type of rule broken give different amounts of points depending on what kind.

Also rules, will have re-do those.. Preferably less strict, no reason to go banning people like crazy unless its a repeated offence of a big rule after clear warning.

**Comment by Kladdkaka** [comment]
Well, personally I think we should move away from being nice with warnings, and fix so you can't break rules like safezoning. If we fix most of the rules that you can break by mistake, then we can make the rules stricter, as there will only be rules you know is illegal.

**Comment by Joannou1** [comment]
Current system is probably fine, we can tweak it as we go.
