### ISSUE TITLE
Rule Books?

### ISSUE THREAD

**Issue by Jeremy9600** [GLServers/GLD#28]
Something like rule books in the /kit starter (or /kit rulebook, doesn't really matter) so players know what the rules are and don't get banned their first month of playing.

**Comment by Joannou1** [comment]
yeah, can't believe we haven't already done this.. needs to be done.

**Comment by Kladdkaka** [comment]
https://bukkit.org/threads/essentials-book-txt.220327/

**Comment by TyJcksn** [comment]
Either a rules book or have a section of spawn dedicated to a info / quiz starter for first time joiners. Honestly thinking of how kids don't like to read I don't think they will go through the book if it's more than two pages but forcing them to start in a building like in old gld will make them see the custom characteristics.

**Comment by Joannou1** [comment]
I think the first page or two needs to be basic information, then saying the next pages will have the rules.

We can still have a rules section somewhere at spawn, it just needs to be organized better.

**Comment by Joannou1** [comment]
I've set up a basic starting kit which comes with a rule book from #62 
The book acts like a lore book and when right clicked 'redeems' it.. and thus teaching the player about /lore and its existence
(this also allows for much easier editing and updating of the book)

![270da](https://cloud.githubusercontent.com/assets/997747/8101700/813f7f8c-0fce-11e5-8979-82f2ebfe468e.png)
