### ISSUE TITLE
Spawn suggestions

### ISSUE THREAD

**Issue by TyJcksn** [GLServers/GLD#30]
https://github.com/GLServers/GLD/issues/19
(The no pvp region plugin)

Moving the spawn to the middle of the map again would allow players to fan out. We could add the plugin that's above and bring back the gold old obsidian line. Not sure what the main spawn would be like but assuming the castle doesn't lag I think that would be good. Another suggestion is having a quiz building like on old gld forcing players to read before they run out and not know what to do.

**Comment by Joannou1** [comment]
That would be a cool thing to do.
At least then we could get rid of the 1-way wall.

I wonder if that nopvp region thing supports that protland plugin...

**Comment by Joannou1** [comment]
New combat tag plugin adds a glass wall for the tagged person so they cannot enter areas that are no-pvp.

Noob spawn now has basic information under it.
Will possibly add announcement/warps that let people know of said info and how to get there if they missed it.

Quests / guides are another thing but should be in a separate issue.
