### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by TyJcksn** [GLServers/GLD#31]
http://prntscr.com/759qii

It may be because i'm using safari but it still needs to be fixed for the many other mac users.

It also plays both the video music and the other music together.

**Comment by TyJcksn** [comment]
This seems pretty sexy,
https://www.mc-market.org/resources/4/

**Comment by TyJcksn** [comment]
Forums reset too, maybe a new, free program? I'll miss my 1.5k+ posts ranking but nothing major lol

**Comment by Joannou1** [comment]
Not too bad, but I did work on the current one for probably longer than I should have.
I think you can download safari for pc, right? If so I may be able to fix it, but it may just be best to leave it until I can get a full website up.

Forumwise, I think vbulletin is still really nice, don't really see why we should ditch it.
(I actually had to pay like $200 for it a few years ago)

**Comment by Kladdkaka** [comment]
I think we just need to change forum theme

**Comment by Kladdkaka** [comment]
http://www.spigotmc.org/threads/nameless-minecraft-website-software.34810/

**Comment by Joannou1** [comment]
Posting this here as well from #53 

http://www.spigotmc.org/resources/communitybridge.2232/

Link up in-game ranks with forum groups.
Extremely useful.

**Comment by Joannou1** [comment]
Work on the new website is going good!
I just got back home, so haven't had an opportunity to do much, but here's a preview for the homepage:
http://gldesert.com/new

**Comment by Joannou1** [comment]
Main features are done for now.
