### ISSUE TITLE
Black market

### ISSUE THREAD

**Issue by Joannou1** [GLServers/GLD#34]
The black market could still be an interesting element..
Thought for that to come back we need to figure out how to change it's location automatically every day or so.

**Comment by Kladdkaka** [comment]
test

**Comment by Vernier-Low** [comment]
In my opinion, I don't think many players will like the idea of combing the desert to find a single black market, knowing that it will change locations the very next day.

**Comment by Kerrus** [comment]
If there were multiple black markets it might work. Maybe a special NPC- non hostile witch?

**Comment by Joannou1** [comment]
Maybe we should limit the black markets to the nexus world somehow..
It would save us the trouble of worrying about multiple markets, and when the change them up.

With nexus world, we may be able to just copy/paste it in somewhere randomly (if chestshops or whatever we are using will allow that)
