### ISSUE TITLE
Non-McMMO Zones

### ISSUE THREAD

**Issue by Joannou1** [GLServers/GLD#37]
Look into non-mcmmo zones for noobs.
If McMMO levels are to be kept high, we need to figure out how to keep it fair for the noobs so that they can train their skills more effectively without rage-quitting.

**Comment by Kladdkaka** [comment]
http://dev.bukkit.org/bukkit-plugins/mcmmo-worldguard/

**Comment by Kladdkaka** [comment]
Moving this to #52 considering we probably won't go with mcmmo pvp
