### ISSUE TITLE
Nexus Event

### ISSUE THREAD

**Issue by Kladdkaka** [GLServers/GLD#4]
From Kerrus

Actually I have a really cool idea. Build a nexus. Like a big gate thing in the middle of the map, and the gate turns on on weekends or something and you can go through and explore a new world, but when you log out or die you get booted back to the normal world

These new worlds could have resources that are inacessible in the main world (get rid of the sell everything market to encourage mining), and the new worlds are only open for so long. Can't make towns in them, but whenever they go through the portal they're wherever they last were on that world.

Inventories transfer, so they can get shit and bring it back, and have a reason to get shit because no sell-everything market encourages players to actually do shit

and then during the last weekend of the month 'the apocalypse' comes to the world before it shuts down, some sort of big special event where players can participate to earn special rewards/xp bonuses/stuff

shit like releasing lots of ender dragons/withers/stuff you might need a plugin for idk

**Comment by Joannou1** [comment]
We need more automated events that people can look forward too.. 
This is pretty sweet, sold!

**Comment by TyJcksn** [comment]
The nexus portal could lead to this, http://www.spigotmc.org/resources/the-underground.715/
I know it costs $$ But it may be possible to work out a deal with the dev and advertise his plugin on the server (or cough cough go by other means)

**Comment by Joannou1** [comment]
Very cool, could always set it so that the world generator chooses a random thing each time it occurs.. So that way it's a mystery, a fun one at that.

**Comment by TyJcksn** [comment]
These could litter the sky;

http://www.minecraft-schematics.com/schematic/2777/

http://www.minecraft-schematics.com/schematic/2778/

**Comment by Joannou1** [comment]
Possibly, or I could set the world gen to make random floating islands at random.

**Comment by Joannou1** [comment]
Note to self: Find pre-made structures and copy the file a few times with different loot stuff in them.
Preferably many many structures and set the rarity to very rare, as to not have repeating structures.

**Comment by TyJcksn** [comment]
Go to google images then type, "Building Pack Schematic"

**Comment by Joannou1** [comment]
Merging this into #42.

(That post has all the fine details and stuff!)
