### ISSUE TITLE
Nexus/Locus world hopping mechanic.

### ISSUE THREAD

**Issue by Kerrus** [GLServers/GLD#42]
Basically it can be opened to a random world, which can be determined from some specific input materials (so people can actually like, contribute resources and shit to it, and help determine where it goes)

Once opened, the nexus will remain open for two weeks to that world, and you can access it through the nexus (appearing out of a much smaller portal in a mini safe-zone). You can go explore, interact, mine, build bases, trade with locals, fight or go questing, and get a number of blocks/resources/items which are not available in the desert. 

However if you die you do not just respawn in that world, you get kicked out, and there's a lockout period (about 30 minutes) before you can re-enter the Nexus. Higher donor ranks reduce that lockout period to a minimum of 5 minutes, and re-entering the nexus puts you at the mini-portal, not wherever you were when you died. 

Obviously you can't sethomes in that world or anything, so planning and safety are very important. 

Anyways, at the end of the two weeks, the apocalypse happens. The moon turns to blood, the sky burns, hell on earth, super powered mobs begin spawning in and wrecking things, ender dragons begin appearing, and at the very end of it, the apocalypse boss appears. We're talking a boss that would take about an hour or two of concerted effort to kill because it has that much HP (it doesn't heal though, and doesn't fly off and disappear if left alone). Anyone who has contributed a certain amount to killing it gets a special reward that lasts for a month, along with a chance at various special loot drops and shit.

If players fail to kill the apocalypse boss, then everyone on that world dies when the countdown hits zero, and the nexus is damaged, taking 24 hours to 'fix' before it can be pointed at a new world.

**Comment by Kerrus** [comment]
Nexus cooldown: Going through the nexus is like going into a 'hardcore' world. If you die, you get kicked out, you lose your stuff, and you're barred from re-entering for a length of time. Say 30 minutes, with the highest igc rank having a cooldown of 15 minutes (donors can get that down to 5 minutes, and whoever holds the apocalypse dragon rank has instant re-entry or something). 

Other thoughts. The 'worlds' accessible through the nexus should have their own civilizations- so city/town gen, villagers- and a plugin to give villagers cool powers so they can actually fight the souped up mobs and shit. Different powers/weapons in the random selection, better AI behaviour (hunters patrol routes, shit like that), and ability to do things like buy unique items from doomed worlds (though the shops vanish if their villager is killed by a mob- players can't kill them). As the apocalypse continues, shops vanish and maybe some sort of convoy/escort minigame, escorting villagers to the portal. 

Other worlds should have other physical laws, stuff like 'lower gravity (high jump), higher gravity (0.5 jump)'. Lack or presence of certain rare or hard to get materials. Special items only available in those worlds- ranging from stuff sold at stores (easy difficulty) to actual stuff you have to go explore/hunting to find in the limited time (2 weeks) before the apocalypse hits. 

The apocalypse starts on friday and ends sunday, and then there's a cooldown period where the Nexus doesn't go anywhere.

**Comment by Joannou1** [comment]
At the very least we can do the automated world generation and what not every two weeks until we can figure out how to get all that custom stuff coded.

But it all sounds very solid, good job coming up with this!

**Comment by Joannou1** [comment]
Moving to post launch to give us some breathing room here.
One week after launch will be the start of the two week cycles, how does that sound?

**Comment by Kerrus** [comment]
sure

**Comment by Joannou1** [comment]
Actually decided to see if I can get the mechanics done now, and then we can open the world after a bit of time.

So far I got the portal mechanics almost complete.
Portals are defined by regions (nexuspe1-4)..
Define the region around the entrance structure and it will create the ender crystal in the middle of that region at the highest block to make it look like your structure on GLD @Kerrus.

Upon entering the portal, it will teleport you to the Nexus world.
The exit destination at the moment is just 0, 0 in the nexus world at the highest block +3.

(Teleport region should ideally be about this size or 1 smaller, can also be large like the top one)
![484e8](https://cloud.githubusercontent.com/assets/997747/8148901/e269dc50-1265-11e5-8899-c9c4e41ebb82.png)

All teleport events check if the world destination is the NexusWorld, if it is, it checks the source to see if it is a portal. If it isn't, it will deny the teleport and state you need to use a portal.
Admins can bypass.

Portals can be deactivated and activated with /nexus open / close.

I'll do the lockout timers and whatnot tomorrow.
Great progress today though.

**Comment by Joannou1** [comment]
All the core mechanics are complete!
Upon user death in the Nexus world users will be locked of for 30 minutes - a modification time based on permissions.

Bypass permission for staff is nexus.bypass.cooldown & nexus.bypass.teleport

Added a set lockout time with /nexus settimer [user] [minutes] 
eg; /nexus settimer BillyBob 10.5

The boss mechanics and world generation stuff will have to be post launch, as it is hard to determine what it should be at the moment.

**Comment by Joannou1** [comment]
The hopping mechanics have been done, see #51 for the boss/end mechanics.
