### ISSUE TITLE
McMMO Super Breaker & Tree Feller

### ISSUE THREAD

**Issue by Kladdkaka** [GLServers/GLD#43]
We should make Super Breaker and Tree Feller as how they we're before. So Super Breaker should be instant on obsidian, and tree feller should work on jungle trees.
Fixes:
<img src="http://i.imgur.com/elJht7f.png">
Make it 20 or something. (advanced.yml)
<img src="http://i.imgur.com/UbnDVhu.png">
Make it higher. (config.yml)

**Comment by Joannou1** [comment]
done and done.
Obsidian breaks much faster with super breaker and trees can now be chopped fully with tree feller.
