### ISSUE TITLE
Donator Kits

### ISSUE THREAD

**Issue by Jeremy9600** [GLServers/GLD#45]
Buy-able kits (kits that do not come with ranks)

_/kit potion_

*every 3 hours

*32 blaze power, 32 sugar, 32 glistening melon, 32 spider eyes, 32 nether warts, 32 bottles

*$30

_/kit war_

*every day

*64 tnt, 64 cobble stone, 32 redstone, 4 levers, 4 water buckets, 5 creeper eggs

*$30

_/kit emerald_

*every day

*250 emeralds (probably change once the economy is actually up & running and more clear

*$35 (probably change)

_/kit mining_

*every 6 hours

*fortune 3, efficiency 3 diamond pickaxe, 64 torches

*$10

Prices & kits themselves will probably vary.

**Comment by Kladdkaka** [comment]
250 emeralds feels a bit too op, other than that I agree

**Comment by Jeremy9600** [comment]
well since I don't know how the economy will be that will probably change, like I had said.

**Comment by TyJcksn** [comment]
Pay to win?

**Comment by Joannou1** [comment]
Closing old submissions that are done.
