### ISSUE TITLE
Bring back Sniper/Archer Packs

### ISSUE THREAD

**Issue by Jeremy9600** [GLServers/GLD#46]
Not sure if anyone remembers the Elemental Arrows but we should bring those back, if possible.

I'm sure James would agree. 8)

**Comment by Kerrus** [comment]
We'd love to, but plugin ded. Maybe if we find a new one.

**Comment by Jeremy9600** [comment]
shame.

**Comment by Kladdkaka** [comment]
ded plugin, if you guys find another alternative just post it here and reopen this ticket.
