### ISSUE TITLE
No Market - but limited spawn shops

### ISSUE THREAD

**Issue by Kerrus** [GLServers/GLD#49]
There was a time that GLD needed a market, when there was lots of demand and it generated lots of revenue for the internal economy, but I think over time it's encouraged lethargy more than anything- players automate the earning process as much as possible, and then just don't play while they rake in all the money that they never use. There's no more informal player trading, there's very little investment in actually getting hard to get resources because you can just buy any item or block in the game from the market.

For the new GLD, I remain adamant that we need to not have a market. 

NPCs that buy refined goods in exchange for emeralds at the spawn? Sure.

Limited shops that sell basic items? Can do.

But a 'sell everything' market? No. Players should have to work for their items, for their first saplings, for their potion ingredients, and their refined items. 

With the world hopping mechanic, most of those items are only a portal away, and we want to encourage play, not afking.

Because wood is obviously in limited supply in the desert, we should have a shop at spawn that sells _sticks_ for use in making tools, or possibly a kit that gives you a half-stack of them or something. 

Other essentials can be sold, but beyond that, all the other stuff should be stuff players have to make or build- to not only increase their play investment, but also give them a sense of accomplishment when they finally get those items, and make war time more important from a griefing/anti griefing perspective rather than just a 'stealing money' perspective.

**Comment by Joannou1** [comment]
This is definitely a great idea, as like you said it encourages more involvement in surviving and really working/earning your place to survive.

The current shop/market area of the spawn would be perfect for that sort stuff.

**Comment by Joannou1** [comment]
Xenu and I were thinking about making a large town where anyone can claim plots and use for shops, but the taxes are so high that it would force them to escalate their prices to compensate.

Any abuse would lead to actions taken.

Thoughts?

**Comment by Joannou1** [comment]
Both have been done, closing this.
