### ISSUE TITLE
Nerf Opples, Limit enchants, Kill pot stacking

### ISSUE THREAD

**Issue by Joannou1** [GLServers/GLD#5]
To balance things and make things more tolerable.
(At the moment it is impossible for a noob to have any chance against a seasoned player)

Matched players should still be able to have a competitive battle, while still being fair for less equipped players.

(Disable Pigmen gold drops, slightly reduce world gold ore gen rate, possibly limit protection to 2 or 3, etc, disable pot stacking once and for all)
^Need to locate methods or plugins to achieve this.

**Comment by Kladdkaka** [comment]
Pretty much making it potpvp :) https://www.youtube.com/watch?v=9wfLO3eCkFA

**Comment by Joannou1** [comment]
I think this is done.
