### ISSUE TITLE
No fly for donors - Instead other transit related donor perk

### ISSUE THREAD

**Issue by Kerrus** [GLServers/GLD#50]
Fly has always been one of the most abused donor ranks, and it's always been something that I think ruins a lot of the experience of playing the game. I don't know if you guys remember, but there was a period on the original server after magic carpet broke down before we had a new fly plugin, and it was some of the best times, since everyone was on the same playing field for traveling, and you couldn't easily get everywhere, or fly above the desert to look for stuff- had to walk everywhere, which meant limited fields of view, need to worry about food, protection from mobs, all that stuff.

I think for the relaunch we should not have fly as a donor perk, though staff would still need it for their duties, but only their duties.

Instead of fly, we could maybe look at summonable horses, possibly where a user could define the type they want, and then they would always be able to summon their horse, which would be tamed and they could ride. It could still die and whatever, and we'd add summoning horses to /ct, but out of combat they could just resummon it. 

This would make horses much more prominent in the game (possibly do a modded horse as a camel) which would add a cool dynamic to naviging the world, and help prevent people from distancing themselves from everything like fly allows.

It'd also mean that people would need to put a lot more effort into building stuff, which I think would make it feel more rewarding, since they can't just fly around and place blocks and the like. 

Thoughts, criticism?

**Comment by Kladdkaka** [comment]
I agree completely +1

**Comment by Jeremy9600** [comment]
great idea. I used to play a RPG server called Dungeonrealms and what they did was have saddles that you'd click to spawn your horse, which was great.

**Comment by Joannou1** [comment]
yeah that would be really good and a bit more in line with the theme/etc.

too much to fix to justify having fly as a perk.
the best I could think of for gaining altitude is MAYBE magic carpet.

**Comment by Joannou1** [comment]
Fully implemented!
(Flying summonable horses)
