### ISSUE TITLE
MCMMO general discussion/suggestions

### ISSUE THREAD

**Issue by Kerrus** [GLServers/GLD#52]
All ranks go to 1200 points, but XP is easier to earn. Makes players feel like they're getting a faster investment even if they're not. All activatable powers for pvp skills unlock at 300, higher stuff at 500 and 800. 

Unarmed - Disarm unlocks at 800 points of unarmed, max % chance is 20%, max iron grip chance is 35%. Raise damage, raise arrow deflect chance, raise berserk length. Make viable style at high levels, but restrict most features (arrow deflect, disarm, iron grip) until later levels. Berserk unlocks at 300, iron arm unlocks immediately, increases in magnitude as levels raise.

Swords - Counter attack unlocks at 800 points of swords, max reflect is 30% of damage while blocking. Bleed doesn't unlock until 500 points. Serrated unlocks at 300. (so basically Swords doesn't actually do anything until 300 points. 

Axes - Skull splitter unlocks at 300. Armor impact caps at like an extra 2 damage to armor, unlocks with value 0.5 extra damage at 800. Greater impact unlocks at 500, Axe Mastery unlocks immediately, starts at 1, goes to max of 4. 

Archery - Skill shot unlocks immediately, Arrow Retrieval unlocks immediately (chance goes up over time. Daze unlocks at 500. 

Non combat skills unlock their stuff earlier and have a larger increase in magnitude as your rank increases.

**Comment by Kladdkaka** [comment]
Great ideas but people doesn't want pvp mcmmo, however we could use then for non-pvp skills +1

**Comment by Joannou1** [comment]
Yeah, this works well because of that reason.. don't want to make it feel like too much of a grind and that their work is visibly paying off quickly.

And like Xenu said, we can adjust it so that the pvp advantages are pretty much null, and that they could be used elsewhere for mobs and whatnot.

**Comment by Jockney** [comment]
I like McMMO and all its features but i hate it when you get lets say.. The bows that would kill you 2 hits without enchantments when the other player is in P4 like what used to happen or the counters.. The days when you just need to bring a bow with 3 arrows, full reg diam and splash the OP enemy with Str2 and blockhit with regen until they died from counters..

**Comment by Kladdkaka** [comment]
From #37

"Look into non-mcmmo zones for noobs.
If McMMO levels are to be kept high, we need to figure out how to keep it fair for the noobs so that they can train their skills more effectively without rage-quitting." - Joan

http://dev.bukkit.org/bukkit-plugins/mcmmo-worldguard/

Considering most people are against mcmmo pvp we probably won't need this plugin, but here is a link in case we do :P

**Comment by Joannou1** [comment]
Ok, doing the advanced settings now.
A lot of these don't have unlock levels though.

#### Unarmed

###### Disarm:

Can't set unlock level (almost all abilities).. But did set max change and at what level the max chance should get attainable. (7% @ 1200).. (Was 33% @ 1000). Enabled anti theft so you cannot steal other players weapons if you do disarm them.

###### Deflect:

Again with the linear scaling of chance -> level.  (25% @ 1200).. (Was 50% @ 1000)

###### Iron Grip:

(35% @ 1200) (Was 100% @ 1000)

###### Iron arm:

Doubled max damage bonus to 16.. min is still 3. Changed damage per level from 50 to 80.

###### Berserk:

Attempted to raise time by 3 seconds.  Most configuration options non existent.

#### Swords

###### Counter:

25% @ 1200 (Was 30% @ 600).. Damage dealt to damager reduced to 1.2x from 2.0x.. requires blocking

###### Bleed:

35% @ 1200 (Was 75% @ 600)

###### Serated:

Basically no configuration.. Reduced damage by almost half, 4 ticks to cause damage from 5.

#### Axes

###### Skull Splitter:

Very little config.. Almost halved damage.

###### Armour Impact:

 Config options are poor.. 1 damage extra per 600 levels. (So 2 cap at 1200). Changed chance from 25% to 5% to compensate.

###### Greater Impact:

Reduced chance from 25% to 15%. Added 25% more knockback. Reduced bonus damage by ~30%.

###### Axe Mastery:

Few options, set max level to 1200 for max bonus of 4.

###### Critical Hit:

Changed max change from 37.5% to 27.5%.. Max is reached at 1200. PVP damage is 1.2 from 1.5. PVE is 2.5 from 2.0.

#### Archery

###### Skill Shot:

Modified levels / percents to scale to current max cap.

###### Arrow Retrieval:

Set max bonus level to 1200 from 1000. Chance is 100% at 1200.

###### Daze:

Max change set to 25% from 50% @ level 1200. Extra damage max is 3 (1.5 hearts.)

...Doing the other non PVP stuff now, will update this post when done.

**Comment by Kerrus** [comment]
Apaprently it's not possible to increase the uptime of individual abilities, but there IS a permission node to globally increase uptime. 

mcmmo.perks.activationtime.fourseconds
mcmmo.perks.activationtime.eightseconds
mcmmo.perks.activationtime.twelveseconds

Are the three nodes in question and will increase all relevant abilities that have an uptime by that amount (I don't think they stack though). 

Here's the full list of the relevant nodes: https://github.com/mcMMO-Dev/mcMMO/wiki/List-of-permissions

**Comment by Joannou1** [comment]
probably don't stack, but we maybe we should give a four second boost to everyone? not sure

**Comment by Kerrus** [comment]
Well honestly we could do what we did with GLD before and stick it on a donor rank. Maybe give what's the middle of the road rank- Nomad? give it to nomad, and then give one of the higher paid ranks the 8 second one?

**Comment by Joannou1** [comment]
That would probably work pretty well for our goal of more progressive perks and less overpowering ones.

**Comment by Joannou1** [comment]
### Non PVP:

###### Warning, just lots of default configs because I am tired and I don't know half of the stuff here :(

###### Feel free to make suggestions for anything critical, or how to go about scaling the different levels, etc.

#### Acrobatics:

###### Dodge:

Scaled to 1200.. cap is currently unlim though. Increased max chance to 30 from 20%.

###### Roll:

Added 100 levels to max bonus level, increased max damage prot to 9 from 7.

###### Graceful Roll:

Added 100 levels to max bonus level. increased max damage prot from 14 16

#### Alchemy:

###### Catalysis:

Changed unlock level / maxbonus from 100 / 1000

```
        UnlockLevel: 200
        MaxBonusLevel: 1200
        MinSpeed: 1.0
        MaxSpeed: 4.0
```

###### Rank_Levels:

Changed from linear scale to exponential

```
        Rank_1: 22
        Rank_2: 44
        Rank_3: 92
        Rank_4: 193
        Rank_5: 355
        Rank_6: 578
        Rank_7: 750
        Rank_8: 1200
```

#### Fishing:

###### Rank_Levels:

Edited to semi linear 1200

```
        Rank_1: 0
        Rank_2: 150
        Rank_3: 300
        Rank_4: 450
        Rank_5: 600
        Rank_6: 700
        Rank_7: 900
        Rank_8: 1200
```

###### ShakeChance:

```
        Rank_1: 15.0
        Rank_2: 15.0
        Rank_3: 25.0
        Rank_4: 35.0
        Rank_5: 45.0
        Rank_6: 55.0
        Rank_7: 65.0
        Rank_8: 80.0

    # VanillaXPMultiplier: Vanilla XP gained from fishing is multiplied by these values.
```

###### VanillaXPMultiplier:

Set rank 8 to 6 from 5

```
        Rank_1: 1
        Rank_2: 2
        Rank_3: 3
        Rank_4: 3
        Rank_5: 4
        Rank_6: 4
        Rank_7: 5
        Rank_8: 6
```

###### FishermansDiet:

200 > 350

```
        # This determines when Fisherman's Diet adds extra hunger recovery to food
        RankChange: 350
```

###### IceFishing:

50>100

```
        # UnlockLevel: Fishing level when the Ice Fishing ability unlocks
        UnlockLevel: 50
```

###### MasterAngler:

125>200

```
        # UnlockLevel: Fishing level when the Master Angler ability unlocks
        # BoatMultiplier: Catch rate is multiplied by this modifier
        # BiomeModifier: Catch rate is multiplied by this modifier
        UnlockLevel: 200
        BoatModifier: 2.0
        BiomeModifier: 2.0
```

#### Herbalism:

Unknown... Cap is 1200.

###### FarmersDiet:

```
        # This determines when Farmers Diet adds extra hunger recovery to food
        RankChange: 200
```

###### GreenThumb:

```
        # StageChange: Level value when the GreenThumb stage rank goes up
        # ChanceMax: Maximum chance of GreenThumb when on <MaxBonusLevel> or higher
        # MaxBonusLevel: On this level, GreenThumb chance will be <ChanceMax>
        StageChange: 200
        ChanceMax: 100.0
        MaxBonusLevel: 1500
```

###### DoubleDrops:

```
        # ChanceMax: Maximum chance of receiving double drops when on <MaxBonusLevel> or higher
        # MaxBonusLevel: Level when <ChanceMax> of receiving double drops is reached
        ChanceMax: 100.0
        MaxBonusLevel: 1000
```

###### HylianLuck:

```
        # ChanceMax: Maximum chance of Hylian Luck when on <MaxBonusLevel> or higher
        # MaxBonusLevel: On this level, Hylian Luck chance will be <ChanceMax>
        ChanceMax: 10.0
        MaxBonusLevel: 1000
```

###### ShroomThumb:

```
        # ChanceMax: Maximum chance of ShroomThumb when on <MaxBonusLevel> or higher
        # MaxBonusLevel: On this level, ShroomThumb chance will be <ChanceMax>
        ChanceMax: 50.0
        MaxBonusLevel: 1500
```

#### Mining:

###### DoubleDrops:

```
        # ChanceMax: Maximum chance of receiving double drops when on <MaxBonusLevel> or higher
        # MaxBonusLevel: Level when <ChanceMax> of receiving double drops is reached
        ChanceMax: 100.0
        MaxBonusLevel: 1000

    # BlastMining_Rank: BlastMining rank unlocks
```

###### BlastMining:

###### Rank_Levels:

Edited linear scale from 1000 to 1200

```
            Rank_1: 150
            Rank_2: 300
            Rank_3: 450
            Rank_4: 600
            Rank_5: 750
            Rank_6: 900
            Rank_7: 1050
            Rank_8: 1200

        # BlastDamageDecrease Ranks: % of damage reduced from TNT explosions
```

###### BlastDamageDecrease:

```
            Rank_1: 0.0
            Rank_2: 0.0
            Rank_3: 0.0
            Rank_4: 25.0
            Rank_5: 25.0
            Rank_6: 50.0
            Rank_7: 50.0
            Rank_8: 100.0

        # OreBonus Ranks: % of extra ores received when Blast Mining
```

###### OreBonus:

```
            Rank_1: 35.0
            Rank_2: 40.0
            Rank_3: 45.0
            Rank_4: 50.0
            Rank_5: 55.0
            Rank_6: 60.0
            Rank_7: 65.0
            Rank_8: 70.0

        # DebrisReduction_Rank: % of fewer non-ores received when Blast Mining
```

###### DebrisReduction:

```
            Rank_1: 10.0
            Rank_2: 20.0
            Rank_3: 30.0
            Rank_4: 30.0
            Rank_5: 30.0
            Rank_6: 30.0
            Rank_7: 30.0
            Rank_8: 30.0

        # DropMultiplier Ranks: # of times each ore will drop
```

###### DropMultiplier:

```
            Rank_1: 1
            Rank_2: 1
            Rank_3: 1
            Rank_4: 1
            Rank_5: 2
            Rank_6: 2
            Rank_7: 3
            Rank_8: 3

        # BlastRadiusModifier Ranks: Increases the blast radius by this amount
```

###### BlastRadiusModifier:

```
            Rank_1: 1.0
            Rank_2: 1.0
            Rank_3: 2.0
            Rank_4: 2.0
            Rank_5: 3.0
            Rank_6: 3.0
            Rank_7: 4.0
            Rank_8: 4.0
```

#### Repair:

###### RepairMastery:

```
        # MaxBonusPercentage: Maximum bonus percentage for Repair Mastery
        # MaxBonusLevel: On this level, the maximum bonus is reached
        MaxBonusPercentage: 200.0
        MaxBonusLevel: 1000
```

###### SuperRepair:

```
        # ChanceMax: Maximum chance of Super Repair when on <MaxBonusLevel> or higher
        # MaxBonusLevel: On this level, Super Repair chance will be <ChanceMax>
        ChanceMax: 100.0
        MaxBonusLevel: 1000
```

###### ArcaneForging:

```
        May_Lose_Enchants: true
```

###### Rank_Levels:

```
            Rank_1: 125
            Rank_2: 250
            Rank_3: 375
            Rank_4: 500
            Rank_5: 625
            Rank_6: 750
            Rank_7: 875
            Rank_8: 1000
```

###### Keep_Enchants_Chance:

```
            Rank_1: 10.0
            Rank_2: 20.0
            Rank_3: 30.0
            Rank_4: 40.0
            Rank_5: 50.0
            Rank_6: 50.0
            Rank_7: 60.0
            Rank_8: 60.0
```

###### Downgrades_Enabled: true

###### Downgrades_Chance:

```
            Rank_1: 75.0
            Rank_2: 50.0
            Rank_3: 40.0
            Rank_4: 30.0
            Rank_5: 25.0
            Rank_6: 20.0
            Rank_7: 15.0
            Rank_8: 10.0
```

#### Salvage:

```
    # MaxPercentage: Maximum percentage of materials to be returned when Salvaging
    # MaxPercentageLevel: On this level, the Salvage percentage will be <MaxPercentage>
```

###### MaxPercentage: 100.0

###### MaxPercentageLevel: 1000

```
    # AdvancedSalvage_UnlockLevel: The level at which Advance Salvage become available
```

###### AdvancedSalvage:

```
        UnlockLevel: 350
```

###### ArcaneSalvage:

```
        # EnchantLossEnabled: When salvaging enchanted items, the enchants may be lost
        # EnchantDowngradeEnabled: When salvaging enchanted items, the enchants may be downgraded
```

###### EnchantLossEnabled: true

###### EnchantDowngradeEnabled: true

###### Rank_Levels:

```
            Rank_1: 125
            Rank_2: 250
            Rank_3: 375
            Rank_4: 500
            Rank_5: 625
            Rank_6: 750
            Rank_7: 875
            Rank_8: 1000

        # ExtractFullEnchant: Chance to extract the full enchant at each ArcaneSalvage rank
```

###### ExtractFullEnchant:

```
            Rank_1: 2.5
            Rank_2: 5.0
            Rank_3: 7.5
            Rank_4: 10.0
            Rank_5: 12.5
            Rank_6: 17.5
            Rank_7: 25.0
            Rank_8: 32.5

        # ExtractPartialEnchant: Chance to extract the partial enchant at each ArcaneSalvage rank
```

###### ExtractPartialEnchant:

```
            Rank_1: 2.0
            Rank_2: 2.5
            Rank_3: 5.0
            Rank_4: 7.5
            Rank_5: 10.0
            Rank_6: 12.5
            Rank_7: 15.0
            Rank_8: 17.5
```

#### Smelting:

###### FuelEfficiency:

```
        # Multiplier: The furnace burn time will be multiplied by this value.
        # MaxBonusLevel: On this level, the efficiency multiplier will stop increasing
        Multiplier: 3.0
        MaxBonusLevel: 1000
```

###### SecondSmelt:

```
        # ChanceMax: Maximum chance of triggering Second Smelt
        # MaxBonusLevel: On this level, the chance to cause Second Smelt will be <ChanceMax>
        ChanceMax: 100.0
        MaxBonusLevel: 1000
```

###### FluxMining:

```
        # UnlockLevel: Level when Flux Mining becomes available
        # Chance: Chance for Flux Mining to activate
        UnlockLevel: 250
        Chance: 33.0

    # Rank_Levels: Smelting level where rank gets unlocked
```

###### Rank_Levels:

```
        Rank_1: 125
        Rank_2: 250
        Rank_3: 375
        Rank_4: 500
        Rank_5: 625
        Rank_6: 750
        Rank_7: 875
        Rank_8: 1000

    # VanillaXPMultiplier: Vanilla XP gained from smelting ores is multiplied by these values.
```

###### VanillaXPMultiplier:

```
        Rank_1: 1
        Rank_2: 2
        Rank_3: 3
        Rank_4: 3
        Rank_5: 4
        Rank_6: 4
        Rank_7: 5
        Rank_8: 5
```

#### Taming:

###### Gore:

```
        # ChanceMax: Maximum chance of triggering gore
        # MaxBonusLevel: On this level, the chance to cause Gore will be <ChanceMax>
        ChanceMax: 100.0
        MaxBonusLevel: 1000

        # BleedTicks: Determines the length of the bleeding effect
        # Modifier: Damage will get multiplied by this modifier
        BleedTicks: 2
        Modifier: 2.0
```

###### FastFood:

```
        # UnlockLevel: Level when FastFood unlocks
        # Chance: The chance for wolves to heal hp when inflicting damage
        UnlockLevel: 50
        Chance: 50.0
```

###### EnvironmentallyAware:

```
        # UnlockLevel: Level when EnvironmentallyAware unlocks
        UnlockLevel: 100
```

###### ThickFur:

```
        # UnlockLevel: Level when ThickFur unlocks
        # Modifier: Damage will get divided by this modifier
        UnlockLevel: 250
        Modifier: 2.0
```

###### HolyHound:

```
        # UnlockLevel: Level when HolyHound unlocks
        UnlockLevel: 375
```

###### ShockProof:

```
        # UnlockLevel: Level when ShockProof unlocks
        # Modifier: Damage will get divided by this modifier
        UnlockLevel: 500
        Modifier: 6.0
```

###### SharpenedClaws:

```
        # UnlockLevel: Level when SharpenedClaws unlocks
        # Bonus: This bonus will get added to the damage caused
        UnlockLevel: 750
        Bonus: 2.0
```

###### CallOfTheWild:

```
        # MinHorseJumpStrength: The minimum jump strength a summoned horse must have
        # MaxHorseJumpStrength: The maximum jump strength a summoned horse can have
        MinHorseJumpStrength: 0.7
        MaxHorseJumpStrength: 2.0
```

###### Pummel:

```
        # ChanceMax: Maximum chance of triggering pummel
        Chance: 10.0
```

#### Woodcutting:

###### LeafBlower:

```
        # UnlockLevel: At this level, the passive ability LeafBlower unlocks
        UnlockLevel: 100
```

###### DoubleDrops:

```
        # ChanceMax: Maximum chance of receiving double drops
        # MaxBonusLevel: Level when the maximum chance of receiving double drops is reached
        ChanceMax: 100.0
        MaxBonusLevel: 1000
```

**Comment by Joannou1** [comment]
I've set up some of the scales and stuff, but a lot of this still needs to be set.

I've also set up the XP modifiers to be exponential progression instead of linear with a 2X rate on XP, and some boosts on mining / acrobatics.

**Comment by Joannou1** [comment]
McMMO seems to be stable at the current set numbers.
