### ISSUE TITLE
New to-do

### ISSUE THREAD

**Issue by Kladdkaka** [GLServers/GLD#59]
Configurate Lottery
Configurate Bloodmoon

**Comment by Joannou1** [comment]
Get a temporary spawn set up
~~Create player market town (disable upkeep or deposit a lot of money via /t deposit)~~
~~Set up community bridge for forums?~~
Create player market spawn

**Comment by Joannou1** [comment]
Spent probably way to much time and energy into community bridge, but good lord it finally works...
Only 'downside' is that the user title will take up to 1 minute max to update upon a forum page refresh.

@Kerrus is working on some buildings for the main spawn, we may just use the unfinished version and keep adding onto that as it gets developed.

Not sure what's up with the player market thing.. Can it even be done properly with Towny @Kladdkaka ?

**Comment by Kladdkaka** [comment]
@Joannou1 everything is done, except that you can't for some reason claim plots (something with economy, not anything wrong with towny plot system)

**Comment by Joannou1** [comment]
I'm assuming claiming plots is critical for it to work? lol
What exactly is the issue, gringotts?

**Comment by Joannou1** [comment]
Mystery solved, the towns vault was simply full!
Took out a row of emerald blocks and claiming worked fine again.
Seems to operate as advertised.

**Comment by Joannou1** [comment]
Updated my mini to-do.
We need a mini spawn area for the player market, something simple.

**Comment by Joannou1** [comment]
Closing this cause of the new checklist todo thing.
