### ISSUE TITLE
Map features

### ISSUE THREAD

**Issue by Joannou1** [GLServers/GLD#6]
If you've seen the Titan world, you've seen that it has A LOT of random structures and random objects that pepper the world and make it fun to explore.

I'll be using some items from the same pack, but if anyone wants to help with unique rare features, feel free to make an object in SP or wherever and leave a screenshot here.

(Map feature files are BO2's)

**Comment by TyJcksn** [comment]
Maybe make the main map smaller, that way players can find other towns and actually be able to raid.

**Comment by Joannou1** [comment]
I think smaller map would be a good idea for many reasons.
It would also encourage use of the nexus more as resources get depleted on the main map.

**Comment by Joannou1** [comment]
So, initial map is code named Mojave.
Map will be 10k x 10k, which is about 9 smaller than our 30k x 30k map.
The name was actually just a coincidence, the Mojave desert is actually about 9 times smaller than the Kalahari (current map name).

Anyways, I'll be doing TC stuff tomorrow, think you could get some people to work on random map items/features?

Need:
-More vegetation (If possible different cactus formations, dead trees, etc)
-Abandoned huts/houses/wells
-A few odd/mysterious structures that look decorative and will spawn rarely.
-Anything else you think would make sense and add to the environment.

**Comment by Joannou1** [comment]
All map features are looking good, we don't really need a ton in all reality.
I'll finalize it later and move it onto build so we can work in the spawns into the permenant position and build from there.

Note to self, do not forget #5 - reduction in gold gen rates.

**Comment by Joannou1** [comment]
Map finalized, completely rendered and checked for errors.
All looks good.

Starting to integrate the spawns and stuff into it now!
