### ISSUE TITLE
GLD Idea

### ISSUE THREAD

**Issue by DAYOLONATER** [GLServers/GLD#60]
I got an idea from a server I play and I think it is a good idea for GLD. mining a spawner with a silk touch pickaxe and the spawner would drop! I was wanting this to be in GLD for a long time and now that the owner is looking for new ideas for the server I decided to share this idea! Picking up a spawner could be only doable by donating or a special package in the shop. and you could make getting silk touch picks harder to get. This is just an idea please tell me what you think! If this was put in it would help the server a lot because people want spawner's so they would donate to be able to mine them and then the server would earn more money. Hope Joannou1 is reading this because it seems to be a good idea to me!

**Comment by Jeremy9600** [comment]
It's already in current GLD.

If we were to add it to new GLD, it should be very expensive because:

*It encourages xRay

*If players were to mine lots of spawners and then set up an incredibly overpowered grinder, they could easily cause lag and also become very rich, very quickly. 

*It would break the economy in a matter of months.

I don't think it'll happen. Sorry buddy.

**Comment by DAYOLONATER** [comment]
But as I said you could make the silk touch pick hard to get and you can only get it through a donation package. also the server would benefit from this a lot. The server I got this idea Is currently doing very good too

**Comment by Kladdkaka** [comment]
Making it a donator package would kill the server, as it already have done

**Comment by DAYOLONATER** [comment]
well can you guys help make this idea better instead of just throwing it away? because if other servers do this and they have a ton of players because of it I don't see why this is such a bad idea

**Comment by Kladdkaka** [comment]
#8 @DAYOLONATER

**Comment by Joannou1** [comment]
We may have the silk spawners thing be a thing, but with a very very low percentage.
