### ISSUE TITLE
Staff Permissions

### ISSUE THREAD

**Issue by Jeremy9600** [GLServers/GLD#65]
-Trial-Mod:
jail, mute, kick

-Mod:
ban, tempban, warn, unban, /staff (staff chat channel for mod - powermod), dwarn, warnings <name> (ability to see other peoples warnings), worldguard, socialspy, vanish, invsee, broadcast

-Power Mod:
IPban, enderchest (ability to see other peoples enderchests), W.E (must apply), TPother

-Admin:
/admin (channel for admins only)

-Head Admin:
gamemode, PEX, basically op

http://prntscr.com/7jki9o

feedback appreciated.

also, if i seem to have forgotten an important permission, be sure to inform me & ill edit the list.

**Comment by Joannou1** [comment]
Most perms should be done, just went over it and added any missing bits.
WG may have to be done later.
Also added the prefixes.
