### ISSUE TITLE
Staff Guide Book

### ISSUE THREAD

**Issue by Jeremy9600** [GLServers/GLD#66]
A book for new staff members, that comes in a special kit called something along the lines of "/kit staffguide", basically explaining the rules and punishments for players who break the rules. I will make this on the server but first I'm going to put this on here in order for anyone to fix my corrections, preferably Kerrus & Joan.

"This book will show you the punishment for players who break the rules:

_Spamming_

If a player is spamming the server, the usual punishment that the player should receive is a mute. The length of the mute will depend on how extreme the spam was. For example: if the player was spamming something offensive such as "faggot", the player should receive a mute no shorter than 1 hour. The player may also receive a warning, depending on how many times he spammed, etc.

_Hacking/Bug Abusing_

If the player is found to be hacking or abusing bugs, the usual punishment that the player should receive is a ban. If the player has abused something serious, like duping, then the player should receive a permanent ban, or ipban. This all depends on how much they duped & what they duped, however.  Keep in mind that if you're suspicious of a player hacking then be sure to screenshare them. If they refuse to screenshare for (insert excuse here), then warn them. If they consistently refuse and are still engaging in suspicious behavior, then a ban is appropriate.

_Abuse of Donator Powers_

If a donator is abusing his powers then the punishment that the player should receive is a warning. However, this all depends on the extremity on the case. If the player has been abusing his donator powers to gain a massive advantage over someone else, for example finding a bug within their perk, then they should be punished with a ban.

_Code of Conduct_

Similar to spamming, if the player breaks the "code of conduct" then they should be muted & warned. Code of conduct is when a player says racist/bigoted terms like "n_gger and f_ggot." If the player is repeatedly spamming words like that, feel free to mute them for however long you think that they deserve it. 

_Staff Abusing/Breaking Rules_

If you have suspicion of a staff member breaking rules/abusing their powers then you should make an effort to get evidence and use any form of effective communication to alert an admin. Sometimes, a staff members' account can be hacked. To notice this, simply do /seen _staff members username_, look at their IP and then type "/seen (IP)" in order to find out if there are any other accounts linked to the staff member that shouldn't be. It is CRUCIAL that you get proof of the staff member abusing. If the staff member had found out to be abusing their power themselves, their punishment will usually have them being stripped from their rank and banned, depending on what they abused and how extreme it was.

_Other_

If a player has broken a rule like TP killing, spawn killing, or even warp abuse, then they should be punished with a warning and a 15 minute jail time. Repeat this punishment if they TP kill, spawn kill, warp abuse, etc. again, by increasing their jail time. The max jail time that you should give is 1 hour."

Once proof read and corrected by someone, I will write this on a book on GLD 3.0 and hopefully have Joan/Kerrus make it into a kit. Be sure to note any mistakes I have made and correct them for me, thanks.

**Comment by Jeremy9600** [comment]
Book finished. Kit will be made & added to trial mod+ whenever Joan is available.

**Comment by Joannou1** [comment]
Forgot to close this.
Book has been added to kit staff and perms given..
