### ISSUE TITLE
Town Owner Activatable War Times

### ISSUE THREAD

**Issue by ryandouglas6** [GLServers/GLD#67]
I think it'd be quite cool if two enemy towns had their owners somehow agree to host a miniature war right then and there for an hour. Griefing, Fire Damage, Explosions etc. would be active in only those two towns for an hour or so. This would solve the problem of feeling bored whilst waiting for the actual wartimes weekly. An owner declining could also show a towns weakness. Maybe the message that the two are at war or one has declined could be globally announced. This would allow bystanders to think about which towns to attack based on their aggressiveness. Not sure how it'd be done. Would be a great later addition.

**Comment by Joannou1** [comment]
Eh, that would be another headache to set up and manage.
We already have the nexus and other things in the works.

The fact that towns are going to be so valuable to raid would make it less valuable if it wasn't restricted to weekly.

**Comment by ryandouglas6** [comment]
Alright
